apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-acr
  namespace: default
spec:
  params:
    - name: image
      description: Full image name including registry
      type: string
    - name: dockerfile
      description: Path to Dockerfile
      type: string
      default: Dockerfile
    - name: context
      description: Build context directory
      type: string
      default: "."

  workspaces:
    - name: source
      description: Source code workspace

  results:
    - name: IMAGE_DIGEST
      description: Digest of the built image
    - name: IMAGE_URL
      description: URL of the built image

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.9.1
      args:
        - --dockerfile=$(workspaces.source.path)/$(params.dockerfile)
        - --context=$(workspaces.source.path)/$(params.context)
        - --destination=$(params.image)
        - --digest-file=$(results.IMAGE_DIGEST.path)
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

    - name: write-url
      image: docker.io/library/bash:5.1.4
      script: |
        set -e
        image="$(params.image)"
        echo -n "${image}" | tee "$(results.IMAGE_URL.path)"

  volumes:
    - name: docker-config
      secret:
        secretName: acr-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
